spring.profiles.active: dev

# 综合配置
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver

    # Show or not log for each sql query
    jpa:
        show-sql: true
        properties:
          hibernate:
            hbm2ddl:
              auto: update
#    devtools:
#        restart:
#            additional-paths: src\\main\\java\\cn\\alandelip

# Swagger配置
swagger:
    title: HTTP API for SpringBoot Template
    api-version: 1.0.0
    description: This is to show http api description
    license: Apache 2.0
    license-url: http://www.apache.org/licenses/LICENSE-2.0.html

---
# 开发环境
spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://localhost:3306/sample
        username: root
        password: root

server:
    port: 8080

spring.jpa.show-sql: false
springfox.documentation.swagger.v2.path: /api-docs
